version: '2.1'
orbs:
 cypress: cypress-io/cypress@3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --spec cypress/e2e/elementInteractions/homework/*.cy.js
          install-browsers: true
  APItests:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --spec cypress/e2e/elementInteractions/APItests/**/*
          install-browsers: true